apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-redis
  template:
    metadata:
      labels:
        app: python-redis
    spec:
      containers:
      - name: python-redis
        image: kl8n/python-redis:latest
        ports:
        - containerPort: 7070
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 7070
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: python-redis-service
spec:
  selector:
    app: python-redis
  ports:
  - port: 7070
    targetPort: 7070
    nodePort: 31111
    protocol: TCP
  type: NodePort
